# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d625c4a200dc1c7dd509665b0a312f70e7562fcf69360aa32f6806b6401175ba7c182bb81d0f6e5cf3d3c83e74af09144ad6b28dc0370dddee7e88d051dd96

test:
  secret_key_base: f683e9902b21c155c0734f4d81c18098a0399dd14556cbe278224faa37ed1343a31693dca29a419ccbde58697c6a0f428380bfb3a754cbdecfff53809e6e5b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
